# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a644d69de25caf987f51966a2292f2fe0e3872bb9b0d313ba2a4de595be12d473c90281ee0f91a4d0f4da4762f390a77a6fdfab515f52fa0c5ce4daf70515b

test:
  secret_key_base: 6a12bc84a299549c79c255daa15f150be49bd60633202e2f88d26ce6c7dcc4b0cc434773fe1c9b544ea05062aebc4f4b2e242d04115992e93bf2753295022c82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
